package com.crittercare.model;

/**
 * Defines the various categories of alerts generated by the simulation engine.
 */
public enum AlertType {

    /**
     * Indicates that an animal's hunger level has reached a critical threshold.
     */
    CRITICAL_HUNGER("Critical Hunger"),

    /**
     * Indicates that an animal's overall health has dropped below acceptable levels.
     */
    LOW_HEALTH("Low Health"),

    /**
     * Signifies that an enclosure's hygiene is poor and requires cleaning.
     */
    DIRTY_ENCLOSURE("Dirty Enclosure"),

    /**
     * Indicates that the number of animals in an enclosure exceeds its maximum capacity.
     */
    OVERCROWDED("Overcrowded"),

    /**
     * Represents an alert triggered when an animal has contracted an illness.
     */
    ANIMAL_SICK("Animal Sick");

    private final String displayName;

    /**
     * Constructs a new alert type with the specified display name.
     *
     * @param displayName the human-readable representation of the alert category
     */
    AlertType(String displayName) {
        this.displayName = displayName;
    }

    /**
     * Retrieves the human-readable display name of the alert type.
     *
     * @return the display name
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Returns the string representation of the alert type.
     *
     * @return the human-readable display name
     */
    @Override
    public String toString() {
        return displayName;
    }
}