package com.crittercare.model;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Represents an actionable alert within the CritterCare system.
 * <p>
 * Alerts are typically generated by the simulation engine or monitoring services
 * when specific thresholds (e.g., critical hunger or low health) are breached.
 * This class encapsulates the alert's origin, severity, and current resolution lifecycle.
 * </p>
 */
public class Alert {

    private static final DateTimeFormatter DISPLAY_FORMAT =
            DateTimeFormatter.ofPattern("MMM dd, yyyy HH:mm");

    private int           id;
    private AlertType     type;
    private AlertSeverity severity;
    private String        sourceId;    // e.g. "ANM-1" or "ENC-3"
    private String        sourceName;  // e.g. "Leo (Lion)"
    private String        message;
    private LocalDateTime timeRaised;
    private String        status;      // "New" | "Acknowledged" | "In Progress" | "Resolved"
    private boolean       resolved;

    /**
     * Default constructor required for framework instantiation.
     * Initializes a new alert with the current timestamp and a default unhandled state.
     */
    public Alert() {
        this.timeRaised = LocalDateTime.now();
        this.status     = "New";
        this.resolved   = false;
    }

    /**
     * Constructs a new alert with the specified details.
     *
     * @param type       the category of the alert
     * @param severity   the urgency level
     * @param sourceId   the system identifier of the origin (e.g., "ANM-1" or "ENC-3")
     * @param sourceName the human-readable name of the origin (e.g., "Leo (Lion)")
     * @param message    the detailed descriptive message
     */
    public Alert(AlertType type, AlertSeverity severity,
                 String sourceId, String sourceName, String message) {
        this();
        this.type       = type;
        this.severity   = severity;
        this.sourceId   = sourceId;
        this.sourceName = sourceName;
        this.message    = message;
    }

    /**
     * Transitions the alert to a resolved state.
     * Flags the alert as resolved and updates its status accordingly.
     */
    public void resolve() {
        this.resolved = true;
        this.status   = "Resolved";
    }

    /**
     * Acknowledges the alert if it is currently in a new state.
     * Transitions the status to acknowledged, indicating staff awareness.
     */
    public void acknowledge() {
        if ("New".equals(this.status)) {
            this.status = "Acknowledged";
        }
    }

    /**
     * Checks whether this alert is newly generated and has not yet been processed.
     *
     * @return {@code true} if the status is new, otherwise {@code false}
     */
    public boolean isNew() {
        return "New".equals(status);
    }

    /**
     * Retrieves the formatted timestamp of when the alert was initially raised.
     *
     * @return the formatted time string, or an empty string if no time is set
     */
    public String getFormattedTimeRaised() {
        return timeRaised != null ? timeRaised.format(DISPLAY_FORMAT) : "";
    }

    @Override
    public String toString() {
        return "[" + severity + "] " + type.getDisplayName() + " – " + sourceName + " (" + status + ")";
    }

    // Getters and Setters

    public int getId() {
        return id;
    }
    public void setId(int id) {
        this.id = id;
    }

    public AlertType getType() {
        return type;
    }
    public void setType(AlertType type) {
        this.type = type;
    }

    public AlertSeverity getSeverity() {
        return severity; }
    public void setSeverity(AlertSeverity severity) {
        this.severity = severity;
    }

    public String getSourceId() {
        return sourceId;
    }
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId;
    }

    public String getSourceName() {
        return sourceName;
    }
    public void setSourceName(String name) {
        this.sourceName = name;
    }

    public String getMessage() {
        return message;
    }
    public void setMessage(String message) {
        this.message = message;
    }

    public LocalDateTime getTimeRaised() {
        return timeRaised;
    }
    public void setTimeRaised(LocalDateTime timeRaised)     {
        this.timeRaised = timeRaised;
    }

    public String getStatus() {
        return status;
    }
    public void setStatus(String status) {
        this.status = status;
    }

    public boolean isResolved() {
        return resolved;
    }
    public void setResolved(boolean resolved) {
        this.resolved = resolved;
    }
}
