package com.crittercare.model;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Represents a system-generated or zookeeper-created alert.
 *
 * Alerts are generated by AlertService when the simulation engine
 * detects a threshold breach (e.g. hunger ≥ 75%).
 *
 * Lifecycle: New → Acknowledged → Resolved
 */
public class Alert {

    private static final DateTimeFormatter DISPLAY_FORMAT =
            DateTimeFormatter.ofPattern("MMM dd, yyyy HH:mm");

    // ── Fields ───────────────────────────────────────────────────────────────

    private int           id;
    private AlertType     type;
    private AlertSeverity severity;
    private String        sourceId;    // e.g. "ANM-1" or "ENC-3"
    private String        sourceName;  // e.g. "Leo (Lion)"
    private String        message;
    private LocalDateTime timeRaised;
    private String        status;      // "New" | "Acknowledged" | "In Progress" | "Resolved"
    private boolean       resolved;

    // ── Constructors ─────────────────────────────────────────────────────────

    public Alert() {
        this.timeRaised = LocalDateTime.now();
        this.status     = "New";
        this.resolved   = false;
    }

    public Alert(AlertType type, AlertSeverity severity,
                 String sourceId, String sourceName, String message) {
        this();
        this.type       = type;
        this.severity   = severity;
        this.sourceId   = sourceId;
        this.sourceName = sourceName;
        this.message    = message;
    }

    // ── Business logic ───────────────────────────────────────────────────────

    /** Moves this alert to Resolved state. */
    public void resolve() {
        this.resolved = true;
        this.status   = "Resolved";
    }

    /** Moves this alert from New to Acknowledged. */
    public void acknowledge() {
        if ("New".equals(this.status)) {
            this.status = "Acknowledged";
        }
    }

    /** Returns true if this alert has not yet been seen by a zookeeper. */
    public boolean isNew() {
        return "New".equals(status);
    }

    /** Returns a formatted time string for display in the UI. */
    public String getFormattedTimeRaised() {
        return timeRaised != null ? timeRaised.format(DISPLAY_FORMAT) : "";
    }

    @Override
    public String toString() {
        return "[" + severity + "] " + type.getDisplayName()
               + " – " + sourceName + " (" + status + ")";
    }

    // ── Getters & Setters ────────────────────────────────────────────────────

    public int getId()                          { return id; }
    public void setId(int id)                   { this.id = id; }

    public AlertType getType()                  { return type; }
    public void setType(AlertType type)         { this.type = type; }

    public AlertSeverity getSeverity()                      { return severity; }
    public void setSeverity(AlertSeverity severity)         { this.severity = severity; }

    public String getSourceId()                 { return sourceId; }
    public void setSourceId(String sourceId)    { this.sourceId = sourceId; }

    public String getSourceName()               { return sourceName; }
    public void setSourceName(String name)      { this.sourceName = name; }

    public String getMessage()                  { return message; }
    public void setMessage(String message)      { this.message = message; }

    public LocalDateTime getTimeRaised()                    { return timeRaised; }
    public void setTimeRaised(LocalDateTime timeRaised)     { this.timeRaised = timeRaised; }

    public String getStatus()                   { return status; }
    public void setStatus(String status)        { this.status = status; }

    public boolean isResolved()                 { return resolved; }
    public void setResolved(boolean resolved)   { this.resolved = resolved; }
}
